const $=id=>document.getElementById(id),N=x=>Number(x)||0,M=x=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(N(x));let sb,user,space,routes=[];const today=()=>{let d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,10)},km=(a,b)=>Math.max(0,N(b)-N(a));function show(id,v){$(id).hidden=!v}function msg(id,t){$(id).textContent=t||''}
async function boot(){if(SUPABASE_URL.includes('COLE_')||SUPABASE_ANON_KEY.includes('COLE_')){msg('authMsg','Configure config.js com URL e chave anon do Supabase.');return}sb=window.supabase.createClient(SUPABASE_URL,SUPABASE_ANON_KEY);let {data:{session}}=await sb.auth.getSession();sb.auth.onAuthStateChange((e,s)=>setTimeout(()=>sessionChanged(s),0));await sessionChanged(session)}
async function sessionChanged(s){user=s?.user;show('auth',!user);show('logout',!!user);if(!user){show('setup',false);show('app',false);return} $('who').textContent=user.email||'Conta Google';let {data,error}=await sb.from('household_members').select('household_id,households(id,name)').eq('user_id',user.id).maybeSingle();if(error){show('setup',true);msg('setupMsg','Execute o SQL de configuração no Supabase. '+error.message);return}if(!data){show('setup',true);show('app',false);return}space=data.households;show('setup',false);show('app',true);$('spaceTitle').textContent=space.name;await load()}
$('login').onclick=async()=>{let {error}=await sb.auth.signInWithPassword({email:$('email').value,password:$('password').value});msg('authMsg',error?.message)};
$('signup').onclick=async()=>{let {error}=await sb.auth.signUp({email:$('email').value,password:$('password').value});msg('authMsg',error?.message||'Conta criada. Confirme o e-mail, se solicitado.')};
$('google').onclick=async()=>{let redirectTo=location.origin+location.pathname;let {error}=await sb.auth.signInWithOAuth({provider:'google',options:{redirectTo}});if(error)msg('authMsg',error.message)};
$('logout').onclick=()=>sb.auth.signOut();
$('createSpace').onclick=async()=>{let {error}=await sb.rpc('create_household',{p_name:$('spaceName').value.trim()});msg('setupMsg',error?.message||'Espaço criado.');if(!error)await sessionChanged({user})};
$('joinSpace').onclick=async()=>{let button=$('joinSpace'),code=$('inviteInput').value.trim();
 if(!code){msg('setupMsg','Informe o código de convite.');return}
 button.disabled=true;button.textContent='Entrando...';msg('setupMsg','Validando código de convite...');
 try{
  const {error}=await sb.rpc('join_household_by_code',{p_code:code});
  if(error){msg('setupMsg',error.message);return}
  msg('setupMsg','Código aceito. Abrindo o espaço...');
  await sessionChanged({user});
 }catch(error){msg('setupMsg',error?.message||'Não foi possível validar o convite. Verifique sua conexão e tente novamente.')}
 finally{button.disabled=false;button.textContent='Entrar com código'}
};
$('invite').onclick=async()=>{let {data,error}=await sb.rpc('create_household_invite');if(error)return alert(error.message);$('inviteCode').textContent='Código: '+data+' (válido por 7 dias; uso único)';navigator.clipboard?.writeText(data)};
async function load(){let {data,error}=await sb.from('routes').select('*').eq('household_id',space.id).order('route_date',{ascending:false});if(error)return alert(error.message);routes=data.map(r=>({id:r.id,date:r.route_date,packages:r.packages,packageCost:+r.package_cost,earnings:+r.earnings,km:+r.total_km,onixKm:+r.onix_km,loganKm:+r.logan_km,oi:r.onix_km_initial,of:r.onix_km_final,li:r.logan_km_initial,lf:r.logan_km_final,notes:r.notes||''}));render()}
function filtered(){let p=$('period').value,d=new Date(),t=today(),s=null,e=null;if(p==='today')s=e=t;if(p==='7'){let x=new Date();x.setDate(x.getDate()-6);s=x.toISOString().slice(0,10);e=t}if(p==='1'){s=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`;e=s.slice(0,8)+'15'}if(p==='2'){s=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-16`;e=new Date(d.getFullYear(),d.getMonth()+1,0).toISOString().slice(0,10)}if(p==='month'){s=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-01`;e=new Date(d.getFullYear(),d.getMonth()+1,0).toISOString().slice(0,10)}return routes.filter(r=>(!s||r.date>=s)&&(!e||r.date<=e))}
function render(){let d=filtered(),g=d.reduce((a,r)=>a+r.earnings,0),p=d.reduce((a,r)=>a+r.packages,0),k=d.reduce((a,r)=>a+r.km,0);$('metrics').innerHTML=[['Rotas',d.length],['Ganhos',M(g)],['Pacotes',p],['KM total',k.toFixed(1)],['R$/KM',M(k?g/k:0)],['R$/pacote',M(p?g/p:0)]].map(([a,b])=>`<span>${a}: ${b}</span>`).join('');$('rows').innerHTML=d.map(r=>`<tr><td>${r.date.split('-').reverse().join('/')}</td><td>${r.packages}</td><td>${r.km} km</td><td>${M(r.packageCost)}</td><td>${M(r.earnings)}</td><td><button onclick="edit('${r.id}')">Editar</button><button onclick="del('${r.id}')">Excluir</button></td></tr>`).join('')}
$('period').onchange=render;const modal=$('modal');$('add').onclick=()=>open();$('cancel').onclick=()=>modal.close();function open(r=null){$('routeForm').reset();$('rid').value=r?.id||'';$('date').value=r?.date||today();$('packages').value=r?.packages??'';$('rate').value=r?.packageCost??'';$('oi').value=r?.oi??'';$('of').value=r?.of??'';$('li').value=r?.li??'';$('lf').value=r?.lf??'';$('notes').value=r?.notes||'';preview();modal.showModal()}
function preview(){let p=N($('packages').value),rate=N($('rate').value),k=km($('oi').value,$('of').value)+km($('li').value,$('lf').value);$('preview').textContent=`Ganho ${M(p*rate)} · KM total ${k} · R$/KM ${M(k?p*rate/k:0)}`}
['packages','rate','oi','of','li','lf'].forEach(id=>$(id).oninput=preview);
$('routeForm').onsubmit=async e=>{e.preventDefault();let oi=N($('oi').value),of=N($('of').value),li=N($('li').value),lf=N($('lf').value),p=N($('packages').value),rate=N($('rate').value);if(of<oi||lf<li)return alert('KM final não pode ser menor que inicial.');let payload={household_id:space.id,route_date:$('date').value,onix_km_initial:oi,onix_km_final:of,onix_km:km(oi,of),logan_km_initial:li,logan_km_final:lf,logan_km:km(li,lf),total_km:km(oi,of)+km(li,lf),packages:p,package_cost:rate,earnings:p*rate,notes:$('notes').value,created_by:user.id};let id=$('rid').value,res=id?await sb.from('routes').update(payload).eq('id',id):await sb.from('routes').insert(payload);if(res.error)return alert(res.error.message);modal.close();await load()};
window.edit=id=>{let r=routes.find(x=>x.id===id);if(r)open(r)};window.del=async id=>{if(confirm('Excluir rota?')){let {error}=await sb.from('routes').delete().eq('id',id);if(error)alert(error.message);else load()}};boot();